linux_host_lifecycle: add lifecycle hooks for Talos workers

diff --git a/modules/puppet/templates/puppet-ubuntu-run-puppet.sh.erb b/modules/puppet/templates/puppet-ubuntu-run-puppet.sh.erb
--- a/modules/puppet/templates/puppet-ubuntu-run-puppet.sh.erb
+++ b/modules/puppet/templates/puppet-ubuntu-run-puppet.sh.erb
@@ -25,6 +25,15 @@ function fail {
     exit 1
 }
 
+# Lifecycle logging is observational only: no failure may interrupt Puppet.
+function lifecycle_log {
+    if [ -x /usr/local/bin/lifecycle-log ]; then
+        if ! /usr/local/bin/lifecycle-log "$@"; then
+            echo "lifecycle-log $* failed; continuing without lifecycle event" >&2
+        fi
+    fi
+}
+
 function extract_username() {
     local url="$1"
     if [[ "$url" =~ git@github.com:([^/]+)/.* ]]; then
@@ -513,6 +522,9 @@ except Exception as e:
 PYEOF
 }
 
+lifecycle_log observe-boot
+lifecycle_log emit puppet_run_started
+
 show_previous_run_status
 echo ""
 
@@ -543,6 +555,7 @@ if [ -n "$WORKER_TYPE_OVERRIDE" ]; then
 fi
 
 # touch the semaphore to let run-start-worker know it can start start-worker
+lifecycle_log emit puppet_run_succeeded
 if [ "$WRITE_SENTINEL" -eq 1 ]; then
     touch "/tmp/puppet_run_done"
 else
