[RELOPS-2104] linux snmp (#1080)

diff --git a/modules/puppet/templates/puppet-ubuntu-run-puppet.sh.erb b/modules/puppet/templates/puppet-ubuntu-run-puppet.sh.erb
--- a/modules/puppet/templates/puppet-ubuntu-run-puppet.sh.erb
+++ b/modules/puppet/templates/puppet-ubuntu-run-puppet.sh.erb
@@ -217,6 +217,13 @@ function run_puppet {
 
 
 # Main script starts here
+
+# Ensure we are running as root
+if [ "$(id -u)" -ne 0 ]; then
+    echo "ERROR: This script must be run as root (current user: $(id -un))." >&2
+    exit 1
+fi
+
 PUPPET_REPO="${PUPPET_REPO:-<%= @puppet_repo -%>}"
 PUPPET_BRANCH="${PUPPET_BRANCH:-<%= @puppet_branch -%>}"
 PUPPET_MAIL="${PUPPET_MAIL:-<%= @puppet_notify_email %>}"
