prevent g-w reboot loop

diff --git a/modules/generic_worker/templates/run-generic-worker.sh.multiuser.erb b/modules/generic_worker/templates/run-generic-worker.sh.multiuser.erb
--- a/modules/generic_worker/templates/run-generic-worker.sh.multiuser.erb
+++ b/modules/generic_worker/templates/run-generic-worker.sh.multiuser.erb
@@ -1,4 +1,10 @@
 #!/bin/bash
+last_premature_end=<%= @user_homedir %>/worker_running_semaphore
+if [ -f $last_premature_end ]; then
+    echo "Last run-generic-worker.sh execution did not complete or completed in less than 120s."
+    sleep 120
+fi
+date > $last_premature_end
 
 # This is a wrapper script for calling generic worker, such that when the worker
 # exits, this script will reboot the machine.
@@ -6,8 +12,8 @@
 (find /private/var/folders/ -nouser -delete; echo "Finished clearing old cache files" ) &
 
 <% if scope.lookupvar('::operatingsystem') == 'Darwin' -%>
-exec 1> >(tee /var/log/genericworker/stdout.log >&1)
-exec 2> >(tee /var/log/genericworker/stderr.log >&2)
+exec 1> >(tee /var/opt/log/generic-worker/stdout.log >&1)
+exec 2> >(tee /var/opt/log/generic-worker/stderr.log >&2)
 <% end %>
 
 # First run the generic-worker, passing through any arguments handed to this
@@ -20,45 +26,46 @@ exec 2> >(tee /var/log/genericworker/stderr.log >&2)
 
 exitstatus="${PIPESTATUS[0]}"
 
-# Remove semaphore file to ensure generic worker does not start before puppet
-rm -rf "/var/tmp/semaphore/run-buildbot"
-
-export TASKCLUSTER_CLIENT_ID="<%= @quarantine_client_id %>"
-export TASKCLUSTER_ACCESS_TOKEN="<%= @quarantine_access_token %>"
-
-if [ $exitstatus -eq 69 ]; then
 # If generic-worker considers that the host environment is in an invalid/corrupted
 # state (for example, it cannot write to disk), it will return the exit code 69.
 #
 # More information about generic-worker exit codes can be seen here:
 # https://docs.taskcluster.net/docs/reference/workers/generic-worker#set-up-your-env
-#
-# If this happens, we make a call to Taskcluster Queue to quarantine the worker, so
-# that no further tasks will be provided to the worker until the quarantine expires.
-# This prevents the worker from burning through tasks that it is not able to execute
-# properly.
-    if [ -f <%= @user_homedir %>/quarantined ]; then
-        echo "Worker is quarantined"
+last_failed_semaphore=<%= @user_homedir %>/worker_exit_69
+if [ $exitstatus -eq 69 ]; then
+    if [ -f $last_failed_semaphore ]; then
+        if [[ $(find "$last_failed_semaphore" -mmin +15 -print) ]]; then
+            echo "Problem repeated for 15m. Sleep 10m ..."
+            sleep 600
+        else
+            echo "Worker repeat exit code 69. Sleep 120s ..."
+            sleep 120
+        fi
     else
-        echo "Quarantine worker"
-        # quarantine the worker using github.com/mozilla-platform-ops/quarantine-worker CLI
-        /usr/local/bin/quarantine-worker releng-hardware "<%= @worker_type %>" "<%= @worker_group %>" "<%= @hostname %>" 720h5s
-
-        # create a semaphore file
-        echo "quarantined worker" > <%= @user_homedir %>/quarantined
+        echo "Exit code 69. Sleep 60s ..."
+        printf "$(date) ${exitstatus}" > $last_failed_semaphore
+        sleep 60
     fi
 elif [ $exitstatus -gt 69 -o $exitstatus -lt 69 ]; then
-    # If exitstatus is different by 69 (grater than 69 or lower than 69)
-    # The worker was removed from the quarantin and run with success a job
-    # Remove quarantined file, if file exist
-    if [ -f <%= @user_homedir %>/quarantined ]; then
-        /bin/rm -rf <%= @user_homedir %>/quarantined
+    if [ -f $last_failed_semaphore ]; then
+        echo "Worker recovered from previous exit code 69."
+        cat $last_failed_semaphore 
+        rm -f $last_failed_semaphore 
     fi
-    # Now reboot the machine immediately (time costs money)
-    <%= @reboot_command %>
-    # Sleep to prevent this script from terminating naturally, and launchd restarting
-    # it. Instead, the shutdown should cause this script to terminate (so it won't
-    # really sleep for 2 mins). If shutdown doesn't kick in within 2 mins, it is sane
-    # for this script to exit, and allow launchd to fire up the worker again.
-    /bin/sleep 120
 fi
+
+# Remove semaphore file to ensure generic worker does not start before puppet
+rm -f "/var/tmp/semaphore/run-buildbot"
+if test $(find $last_premature_end -mmin +2); then
+    rm -f $last_premature_end
+else
+    echo "Leaving so soon! What happened?!"
+    sleep 300
+fi
+
+<%= @reboot_command %>
+# Sleep to prevent this script from terminating naturally, and launchd restarting
+# it. Instead, the shutdown should cause this script to terminate (so it won't
+# really sleep for 2 mins). If shutdown doesn't kick in within 2 mins, it is sane
+# for this script to exit, and allow launchd to fire up the worker again.
+sleep 120
